{"errorMessage": "An error occurred (AuthorizationError) when calling the Publish operation: User: arn:aws:sts::485147667400:assumed-role/trnpreproduction-use1-Dev-User-Credentials-exec-role/trnpreproduction-use1-Dev-User-Credentials is not authorized to perform: SNS:Publish on resource: arn:aws:sns:us-east-1:485147667400:SSMautomationtopic because no identity-based policy allows the SNS:Publish action", "errorType": "AuthorizationErrorException", "requestId": "08970181-3770-4d44-82cc-6d3a3494b15f", "stackTrace": ["  File \"/var/task/lambda_handler.py\", line 56, in lambda_handler\n    send_sns_notification(topic_arn, message_body)\n", "  File \"/var/task/notifier.py\", line 5, in send_sns_notification\n    sns.publish(\n", "  File \"/opt/python/botocore/client.py\", line 595, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/opt/python/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/opt/python/botocore/client.py\", line 1058, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}